AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**
    - config/**/*
    - spec/**/*
Documentation:
  Enabled: false
LineLength:
  Enabled: true
  Max: 160
AbcSize:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
