development:
  clients:
    default:
      database: sav_study_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: sav_study_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
